# Generated by Django 3.1.14 on 2026-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('aicte_id', models.CharField(blank=True, help_text='AICTE permanent ID if available', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
            },
        ),
    ]
